---
name: adc-dac-dma
board: boards/red-pitaya
version: 0.5.0

cores:
  - fpga/cores/redp_adc_v1_0
  - fpga/cores/redp_dac_v1_0
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/dna_reader_v1_0
  - fpga/cores/edge_detector_v1_0
  - fpga/cores/comparator_v1_0
  - fpga/cores/tlast_gen_v1_0

memory:
  - name: control
    offset: '0x40000000'
    range: 4K
  - name: status
    offset: '0x50001000'
    range: 4K
  - name: xadc
    offset: '0x43C00000'
    range: 64K
  - name: ram_mm2s
    offset: '0x1E000000'
    range: 16M
  - name: ram_s2mm
    offset: '0x1F000000'
    range: 16M
  - name: dma
    offset: '0x40400000'
    range: 64K
  - name: axi_hp0
    offset: '0xF8008000'
    range: 4K
  - name: axi_hp2
    offset: '0xF800A000'
    range: 4K
  - name: ocm_mm2s
    offset: '0xFFFF0000'
    range: 32K
  - name: ocm_s2mm
    offset: '0xFFFF8000'
    range: 32K
  - name: sclr
    offset: '0xF8000000'
    range: 64K


control_registers:
  - led
  - trig

status_registers:
  - reg1

parameters:
  fclk0: 143000000
  adc_clk: 125000000
  dac_width: 14
  adc_width: 14
  n_adc: 2

    

xdc:
  - boards/red-pitaya/config/ports.xdc
  - boards/red-pitaya/config/clocks.xdc

drivers:
  - server/drivers/common.hpp
  - ./adc_dac_dma.hpp

web:
  - web/index.html
  - web/main.css
  - web/koheron.ts
